-- =========================================================
-- AUTO-GENERATED SQL IMPORT SCRIPT FROM CSV FILES
-- =========================================================

-- IMPORT: achievements_rows.csv -> achievements table
INSERT INTO public.achievements (title, student_name, description, category, year) VALUES ('Expansion into PG Courses', '', 'The institution later expanded into postgraduate education including MA, MSc, and MCom programs.', 'Postgraduate Education', '');
INSERT INTO public.achievements (title, student_name, description, category, year) VALUES ('Strong Sports Performance', '', 'Students from the college regularly participate in district and university-level sports competitions including cricket, football, volleyball, kabaddi, and athletics.', 'Sports', '');
INSERT INTO public.achievements (title, student_name, description, category, year) VALUES ('Active NCC and NSS Programs', '', 'The college actively conducts NCC and NSS activities including social service, leadership camps, and awareness programs.', 'NCC/NSS', '');
INSERT INTO public.achievements (title, student_name, description, category, year) VALUES ('Center of Excellence / Model College', '', 'Recognized by the Rajasthan Government as a Model College and Center of Excellence for higher education.', 'Education', '');
INSERT INTO public.achievements (title, student_name, description, category, year) VALUES ('Early Introduction of Commerce Stream', '', 'The college introduced Commerce education in 1949, becoming one of the early institutions in the region to offer commerce studies.', 'Commerce Education', '1949');
INSERT INTO public.achievements (title, student_name, description, category, year) VALUES ('Large Campus and Advanced Facilities', '', 'The college has a large campus with science laboratories, library, sports grounds, classrooms, and hostel facilities.', 'Infrastructure', '');
INSERT INTO public.achievements (title, student_name, description, category, year) VALUES ('Prime Location Near Railway Station', '', 'The college is located near Churu Railway Station, making transportation convenient for students from nearby regions.', 'Location', '');
INSERT INTO public.achievements (title, student_name, description, category, year) VALUES ('NAAC Accredited Institution', '', 'The college has received NAAC accreditation and actively operates IQAC for quality improvement in education.', 'Accreditation', '');
INSERT INTO public.achievements (title, student_name, description, category, year) VALUES ('Historic Government College Since 1945', '', 'Government Lohia College Churu is one of the oldest and most prestigious government colleges in Rajasthan, established in 1945.', 'College Achievement', '1945');
INSERT INTO public.achievements (title, student_name, description, category, year) VALUES ('Leading Government College of Churu Region', '', 'Government Lohia College is considered one of the most well-known government colleges in Churu for Arts, Commerce, and Science education.', 'Academics', '');

-- IMPORT: college_kb_rows.csv -> college_faqs table
INSERT INTO public.college_faqs (question, answer, category) VALUES ('What are the college canteen timings and popular items?', 'The Lohia College canteen is open from 9:30 AM to 3:30 PM on all working days. Popular items include hot Samosas (Rs. 10), Chai (Rs. 5), Bread Pakora (Rs. 12).', 'Canteen');
INSERT INTO public.college_faqs (question, answer, category) VALUES ('What is the procedure to issue books from the college library?', 'Present a valid Library Card. Issue up to 2 books for 14 days. Late fee of Rs. 1 per day.', 'Library');
INSERT INTO public.college_faqs (question, answer, category) VALUES ('Are there parking fees or rules for student vehicles on campus?', 'Student parking is near the main gate. Bicycle parking is free. Two-wheelers need valid college ID passes. No fees for regular students.', 'Parking & Campus');
INSERT INTO public.college_faqs (question, answer, category) VALUES ('What are the college canteen timings and popular items?', 'The Lohia College canteen is open from 9:30 AM to 3:30 PM on all working days. Popular items include hot Samosas (Rs. 10), Chai (Rs. 5), Bread Pakora (Rs. 12).', 'Canteen');
INSERT INTO public.college_faqs (question, answer, category) VALUES ('How can a student join the NSS unit of Lohia College?', 'Lohia College has active NSS units. Applications for registration in NSS start in July/August every year. Students can contact the NSS Program Officers in their respective departments to get the application form. Selection is done on a merit and interview basis.', 'NSS & NCC');
INSERT INTO public.college_faqs (question, answer, category) VALUES ('Are there parking fees or rules for student vehicles on campus?', 'Student parking is near the main gate. Bicycle parking is free. Two-wheelers need valid college ID passes. No fees for regular students.', 'Parking & Campus');
INSERT INTO public.college_faqs (question, answer, category) VALUES ('Are there parking fees or rules for student vehicles on campus?', 'Student parking is located near the main entrance gate. Bicycle parking is free of charge. Two-wheelers (motorcycles/scooters) must have valid college ID passes to enter. No parking fees are charged to regular college students with proper ID.', 'Parking & Campus');
INSERT INTO public.college_faqs (question, answer, category) VALUES ('What is the procedure to issue books from the college library?', 'To issue books, students must present a valid Library Card which is made in the beginning of the semester. A student can issue up to 2 books at a time for a duration of 14 days. A late fee of Rs. 1 per day is charged for overdue books.', 'Library');
INSERT INTO public.college_faqs (question, answer, category) VALUES ('What is the procedure to issue books from the college library?', 'Present a valid Library Card. Issue up to 2 books for 14 days. Late fee of Rs. 1 per day.', 'Library');
INSERT INTO public.college_faqs (question, answer, category) VALUES ('What are the college canteen timings and popular items?', 'The Lohia College canteen is open from 9:30 AM to 3:30 PM on all working days (Monday to Friday). Popular items include hot Samosas (Rs. 10 each), Chai (Rs. 5), Bread Pakora (Rs. 12), and cold beverages.', 'Canteen');
INSERT INTO public.college_faqs (question, answer, category) VALUES ('How can a student join the NSS unit of Lohia College?', 'Applications start in July/August. Contact NSS Program Officers in your department. Selection is merit and interview based.', 'NSS & NCC');
INSERT INTO public.college_faqs (question, answer, category) VALUES ('How can a student join the NSS unit of Lohia College?', 'Applications start in July/August. Contact NSS Program Officers in your department. Selection is merit and interview based.', 'NSS & NCC');

-- IMPORT: exam_passing_rules_rows.csv -> college_knowledge table
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('Exam Rule', 'exam_commerce_eafm', 'Passing Rules: Commerce EAFM', 'Subject: EAFM. Theory Max/Min: 200/72. Practical Max/Min: 0/0. Total: 200. Notes: 2 papers of 100 marks each.') ON CONFLICT (search_key) DO NOTHING;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('Exam Rule', 'exam_compulsory_elementarycomputerapplications', 'Passing Rules: Compulsory Elementary Computer Applications', 'Subject: Elementary Computer Applications. Theory Max/Min: 100/36. Practical Max/Min: 0/0. Total: 100. Notes: Mandatory passing score 36%.') ON CONFLICT (search_key) DO NOTHING;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('Exam Rule', 'exam_science_physics', 'Passing Rules: Science Physics', 'Subject: Physics. Theory Max/Min: 135/48. Practical Max/Min: 65/24. Total: 200. Notes: 3 papers of 45 marks each. 36% aggregate in theory + 36% in practical required.') ON CONFLICT (search_key) DO NOTHING;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('Exam Rule', 'exam_arts_generalhindihistorypolscsociologyetc', 'Passing Rules: Arts General (Hindi, History, Pol Sc, Sociology, etc.)', 'Subject: General (Hindi, History, Pol Sc, Sociology, etc.). Theory Max/Min: 200/72. Practical Max/Min: 0/0. Total: 200. Notes: 2 papers of 100 marks each.') ON CONFLICT (search_key) DO NOTHING;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('Exam Rule', 'exam_compulsory_environmentalstudies', 'Passing Rules: Compulsory Environmental Studies', 'Subject: Environmental Studies. Theory Max/Min: 100/36. Practical Max/Min: 0/0. Total: 100. Notes: Mandatory passing score 36%.') ON CONFLICT (search_key) DO NOTHING;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('Exam Rule', 'exam_compulsory_generalenglish', 'Passing Rules: Compulsory General English', 'Subject: General English. Theory Max/Min: 100/36. Practical Max/Min: 0/0. Total: 100. Notes: Mandatory passing score 36%.') ON CONFLICT (search_key) DO NOTHING;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('Exam Rule', 'exam_science_zoology', 'Passing Rules: Science Zoology', 'Subject: Zoology. Theory Max/Min: 135/48. Practical Max/Min: 65/24. Total: 200. Notes: 3 papers of 45 marks each. 36% aggregate in theory + 36% in practical required.') ON CONFLICT (search_key) DO NOTHING;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('Exam Rule', 'exam_arts_homescience', 'Passing Rules: Arts Home Science', 'Subject: Home Science. Theory Max/Min: 150/54. Practical Max/Min: 50/18. Total: 200. Notes: 2 papers of 75 marks each + Practical.') ON CONFLICT (search_key) DO NOTHING;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('Exam Rule', 'exam_science_chemistry', 'Passing Rules: Science Chemistry', 'Subject: Chemistry. Theory Max/Min: 135/48. Practical Max/Min: 65/24. Total: 200. Notes: 3 papers of 45 marks each. 36% aggregate in theory + 36% in practical required.') ON CONFLICT (search_key) DO NOTHING;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('Exam Rule', 'exam_commerce_businessadministration', 'Passing Rules: Commerce Business Administration', 'Subject: Business Administration. Theory Max/Min: 200/72. Practical Max/Min: 0/0. Total: 200. Notes: 2 papers of 100 marks each.') ON CONFLICT (search_key) DO NOTHING;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('Exam Rule', 'exam_commerce_abst', 'Passing Rules: Commerce ABST', 'Subject: ABST. Theory Max/Min: 200/72. Practical Max/Min: 0/0. Total: 200. Notes: 2 papers of 100 marks each.') ON CONFLICT (search_key) DO NOTHING;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('Exam Rule', 'exam_arts_psychology', 'Passing Rules: Arts Psychology', 'Subject: Psychology. Theory Max/Min: 150/54. Practical Max/Min: 50/18. Total: 200. Notes: 2 papers of 75 marks each + Practical.') ON CONFLICT (search_key) DO NOTHING;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('Exam Rule', 'exam_arts_geography', 'Passing Rules: Arts Geography', 'Subject: Geography. Theory Max/Min: 150/54. Practical Max/Min: 50/18. Total: 200. Notes: 2 papers of 75 marks each + Practical.') ON CONFLICT (search_key) DO NOTHING;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('Exam Rule', 'exam_compulsory_generalhindi', 'Passing Rules: Compulsory General Hindi', 'Subject: General Hindi. Theory Max/Min: 100/36. Practical Max/Min: 0/0. Total: 100. Notes: Mandatory passing score 36%.') ON CONFLICT (search_key) DO NOTHING;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('Exam Rule', 'exam_science_mathematics', 'Passing Rules: Science Mathematics', 'Subject: Mathematics. Theory Max/Min: 200/72. Practical Max/Min: 0/0. Total: 200. Notes: 3 papers of 66, 66, and 68 marks. No practical.') ON CONFLICT (search_key) DO NOTHING;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('Exam Rule', 'exam_science_botany', 'Passing Rules: Science Botany', 'Subject: Botany. Theory Max/Min: 135/48. Practical Max/Min: 65/24. Total: 200. Notes: 3 papers of 45 marks each. 36% aggregate in theory + 36% in practical required.') ON CONFLICT (search_key) DO NOTHING;

-- IMPORT: college_milestones_rows.csv -> college_knowledge table
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('History', 'milestone_2010', 'Milestone 2010', 'PG in Urdu introduced') ON CONFLICT (search_key) DO NOTHING;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('History', 'milestone_1954', 'Milestone 1954', 'Faculty of Arts started (English, Hindi, History, Pol Science)') ON CONFLICT (search_key) DO NOTHING;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('History', 'milestone_1955', 'Milestone 1955', 'Faculty of Science started (Zoology, Botany, Chemistry, Physics, Maths)') ON CONFLICT (search_key) DO NOTHING;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('History', 'milestone_1945', 'Milestone 1945', 'Established as Intermediate College') ON CONFLICT (search_key) DO NOTHING;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('History', 'milestone_1949', 'Milestone 1949', 'Upgraded as Degree College with Faculty of Commerce') ON CONFLICT (search_key) DO NOTHING;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('History', 'milestone_1970', 'Milestone 1970', 'Recognized by UGC (2f and 12B)') ON CONFLICT (search_key) DO NOTHING;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('History', 'milestone_1974', 'Milestone 1974', 'Post Graduation in Chemistry started') ON CONFLICT (search_key) DO NOTHING;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('History', 'milestone_1972', 'Milestone 1972', 'Upgraded to Post Graduate level in Commerce') ON CONFLICT (search_key) DO NOTHING;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('History', 'milestone_1993', 'Milestone 1993', 'First Govt college in Rajasthan to start UGC Vocational Communicative English') ON CONFLICT (search_key) DO NOTHING;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('History', 'milestone_2004', 'Milestone 2004', 'Accredited as B+ by UGC') ON CONFLICT (search_key) DO NOTHING;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('History', 'milestone_1977', 'Milestone 1977', 'Post Graduation in History and Political Science') ON CONFLICT (search_key) DO NOTHING;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('History', 'milestone_1982', 'Milestone 1982', 'PG in Zoology and UG in Urdu started') ON CONFLICT (search_key) DO NOTHING;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('History', 'milestone_2018', 'Milestone 2018', 'PG in Hindi started') ON CONFLICT (search_key) DO NOTHING;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('History', 'milestone_2006', 'Milestone 2006', 'Declared a Model College by Govt of Rajasthan') ON CONFLICT (search_key) DO NOTHING;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('History', 'milestone_1999', 'Milestone 1999', 'PG in Geography introduced') ON CONFLICT (search_key) DO NOTHING;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('History', 'milestone_1980', 'Milestone 1980', 'Post Graduation in Botany') ON CONFLICT (search_key) DO NOTHING;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('History', 'milestone_1957', 'Milestone 1957', 'Economics added to Faculty of Arts') ON CONFLICT (search_key) DO NOTHING;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('History', 'milestone_2013', 'Milestone 2013', 'NAAC awarded "B" certificate; Online Admission started') ON CONFLICT (search_key) DO NOTHING;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('History', 'milestone_2016', 'Milestone 2016', 'PG in Maths, Physics, Sanskrit started; UG in Public Admin') ON CONFLICT (search_key) DO NOTHING;

-- IMPORT: college_sections_rows.csv -> college_knowledge table
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('General Info', 'history', 'College History Summary', 'Established in 1945 at intermediate level with 47 students. Shifted to the present location in 1949 and upgraded to graduation level in Commerce. Seth K.L. Lohia built the original huge building, and more additions have been made over time. It was declared a Model College by the Govt of Rajasthan in 2006.') ON CONFLICT (search_key) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('General Info', 'library', 'College Library & Reading Room', 'The library is rich with over 100,184 books. It includes a UGC section (28,932 books), SC/ST section (4,463 books), General section (62,161 books), and RUSA section (4,628 books). It subscribes to 43 journals and magazines, and several newspapers (Dainik Bhaskar, Rajasthan Patrika, etc.). Students have free access to open shelves.') ON CONFLICT (search_key) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('General Info', 'founder', 'Founder: Seth Kanhiya Lal Lohia (1884-1957)', 'Seth Kanhiya Lal Lohia was an eminent entrepreneur doing a brisk jute business in Calcutta. He dreamed of building a college in his home town for a holy cause during the pre-independence era. He is a visionary who brought this desert town on the educational map. Churu came to be known by Lohia College because of its excellent infrastructure and standards. This uneducated businessman had incredible foresight, providing higher education opportunities when facilities were far away.') ON CONFLICT (search_key) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('General Info', 'exam_general', '1. MGSU Examination Overview', 'Maharaja Ganga Singh University (MGSU) follows both Semester and Annual systems.
- Semester System: Jan-June (Sem 2, 4, 6) and July-Dec (Sem 1, 3, 5).
- CBCS (Choice Based Credit System): Includes internal assessment (20 marks) and external university exams (80 marks).
- Internal Assessment: Includes assignments (5), attendance (5), and unit tests (10 marks).') ON CONFLICT (search_key) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('General Info', 'exam_cbc_grading', '5. CBCS Grading (SGPA/CGPA)', 'MGSU uses a letter grade system:
- O (90-100%): Outstanding
- A+ (80-89%): Excellent
- A (70-79%): Very Good
- B+ (60-69%): Good
- B (50-59%): Above Average
- F (Below 36%): Fail (Result shows RT - Reappear in Theory)') ON CONFLICT (search_key) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('General Info', 'hostel', 'Hostel Facility', 'The hostel is situated on the college campus itself, just a stone''s throw from the main college building. It is among the largest (perhaps the largest one) in Rajasthan with 128 rooms, one auditorium, and playgrounds. This is to say something about the farsightedness of that great visionary, Seth Kanhaiya Lal Lohia, that he built such a big hostel at a time when there was absolutely no need of such a big size. The fee structure is very reasonable and even poor students can afford it.') ON CONFLICT (search_key) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('General Info', 'vision', 'College Vision', 'To become a center of academic excellence by providing quality education, practical training, and research opportunities that shape responsible and capable citizens for the future.') ON CONFLICT (search_key) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('General Info', 'mission', 'College Mission', '1. To provide inspired learning and construct value based education system.\n2. To ensure exposure to diverse disciplines.\n3. To encourage merit and enhance employability skills.\n4. To instil a culture of hands-on learning and research.\n5. To impart quality education at an affordable price.\n6. To make available quality education to disadvantageous, marginalized and differently able students.\n7. To lay stress on holistic development of the students’ personality by ensuring their participation in co-curricular and extra-curricular activities.\n8. To inculcate scientific temperament and make them technology-savvy and eco-friendly.') ON CONFLICT (search_key) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('General Info', 'exam_theory', '2. Theory Exam Pattern', 'Theory papers are divided into:
- Section A: 10 Very Short Answer questions.
- Section B: 5 Short Answer questions (approx 25 marks).
- Section C: 3 Long Answer questions (approx 45 marks).
Total Theory Marks: 80 or 100 depending on the subject. Passing requires approx 36% (29 out of 80).') ON CONFLICT (search_key) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('General Info', 'exam_passing', '4. Passing & Back Rules', '- Minimum Passing: 36% overall (separately in Theory and Practical).
- Back/Due System: If a student fails 1-2 papers, they can reappear in the next session.
- Grace Marks: 1-3 marks can be awarded by the university for borderline cases.
- Division System: 60%+ (1st Div), 50-59% (2nd Div), 36-49% (Pass Div).') ON CONFLICT (search_key) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.college_knowledge (category, search_key, title, content) VALUES ('General Info', 'exam_practical', '3. Practical Examination System (Science & Arts)', 'Practical exams are mandatory for Science (Physics, Chemistry, Bio), Geography, and Psychology.
- Science Pattern: Experiment (15), Viva (5), Record File (5), Attendance (5). Total 30 Marks.
- Arts (Geography): Theory (75), Practical (25) including Map work, File, and Viva.
- Passing Practical: Fails in practical mean a Back/Due result. Min 11 marks out of 30 or 18 out of 50 are required.
- Viva-Voce: Oral examination where external examiners ask about definitions, instruments, and experiments.') ON CONFLICT (search_key) DO UPDATE SET content = EXCLUDED.content;

